### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by TomScottDied** [jzohrab/lute-v3#145]
I am using windows 11, 64 bit and have installed mecab because I'm trying to do Japanese.
This is my first time using lute. I'm using chrome and installed lute using python today (18 jan 2024)

If I try to create a new book and hit save it says "500 internal sever error" and the following error message comes up

Traceback (most recent call last):
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\lute\book\routes.py", line 106, in new
    book = repo.add(b)
           ^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\lute\book\model.py", line 58, in add
    dbbook = self._build_db_book(book)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\lute\book\model.py", line 84, in _build_db_book
    b = DBBook.create_book(book.title, lang, book.text)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\lute\models\book.py", line 114, in create_book
    tokens = language.parser.get_parsed_tokens(fulltext, language)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\lute\parse\space_delimited_parser.py", line 33, in get_parsed_tokens
    return self._parse_to_tokens(clean_text, language)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\lute\parse\space_delimited_parser.py", line 66, in _parse_to_tokens
    self.parse_para(para, lang, tokens)
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\lute\parse\space_delimited_parser.py", line 87, in parse_para
    m = self.preg_match_capture(pattern, text)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\lute3\envlute\Lib\site-packages\lute\parse\space_delimited_parser.py", line 42, in preg_match_capture
    matches = re.finditer(pattern, subject, flags=re.IGNORECASE)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\__init__.py", line 224, in finditer
    return _compile(pattern, flags).finditer(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\__init__.py", line 307, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\_compiler.py", line 745, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\_parser.py", line 979, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\_parser.py", line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\_parser.py", line 862, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\_parser.py", line 460, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\_parser.py", line 573, in _parse
    code1 = _class_escape(source, this)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\re\_parser.py", line 366, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 37

**Comment by TomScottDied** [comment]
I fixed the issue. The japanese default setting have "Parse as" set as space delimted. When changed to Japanese it works fine.
