### ISSUE TITLE
Bug(ish): New book from empty file half-creates a new book

### ISSUE THREAD

**Issue by jamesdeluk** [jzohrab/lute-v3#335]
EDIT: OK, it was me being stupid, but still kind of a bug.

If the text file is empty (🤦🏻), it half-creates a new book.

It takes you to the reading page, and the tab title of the reading page is correct:

![image](https://github.com/jzohrab/lute-v3/assets/27723508/8bace955-a503-4ca7-b183-ccf7fe767003)

The console throws an error:

```
ERROR:lute.app_factory:Exception on /read/renderpage/69/0 [GET]
Traceback (most recent call last):
  File "C:\Users\user\Documents\Lute3\envlute\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\Documents\Lute3\envlute\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\Documents\Lute3\envlute\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\Documents\Lute3\envlute\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\user\Documents\Lute3\envlute\lib\site-packages\lute\read\routes.py", line 168, in render_page
    paragraphs = start_reading(book, pagenum, db.session)
  File "C:\Users\user\Documents\Lute3\envlute\lib\site-packages\lute\read\service.py", line 77, in start_reading
    text = dbbook.text_at_page(pagenum)
  File "C:\Users\user\Documents\Lute3\envlute\lib\site-packages\lute\models\book.py", line 110, in text_at_page
    return self.texts[pagenum - 1]
IndexError: list index out of range
```

No book is created on the homepage. Every time I do this, book ID (69 above) increases, and using the /read/ID/page/1 URL I can now "access" several blank books (with correct tab titles). /read/editpage/ID/1 throws the same error as above. So, they seem to half-exist, but cannot be deleted or edited.

Perhaps add some checking function to avoid this?

**Comment by jzohrab** [comment]
Good call, thank you!  Funny, I thought this was handled, obviously not.

**Comment by jzohrab** [comment]
Fixed in develop, it now stops if the file used results in an empty book.

**Comment by jzohrab** [comment]
Launched in 3.3.0.
